### ISSUE TITLE
 float array with point (.)

### ISSUE THREAD

**Issue by avelino** [rumlang/rum#57]
ref #49 

```
▶ go run gin.go
>>> (print array(1.3))
runtime error: Panic[0] - reflect: call of reflect.Value.Call on float64 Value
  # triggered at:
    (print array(1.3))
    ----------------^
  # called from:
    (print array(1.3))
    -----------------^
  # Interpreter trace:
    goroutine 1 [running]:
    github.com/gin-lang/gin/runtime.(*Context).eval.func1.1(0xc420053a90, 0xc420053a60)
        /home/avelino/src/github.com/gin-lang/gin/runtime/runtime.go:168 +0x90
    panic(0x529da0, 0xc42000c220)
        /usr/lib/go/src/runtime/panic.go:491 +0x283
    reflect.flag.mustBe(0x8e, 0x13)
        /usr/lib/go/src/reflect/value.go:201 +0xc8
    reflect.Value.Call(0x51c280, 0xc4200ee198, 0x8e, 0x0, 0x0, 0x0, 0x0, 0xc420053908, 0x4103e7)
        /usr/lib/go/src/reflect/value.go:300 +0x38
    github.com/gin-lang/gin/runtime.(*Context).dispatch(0xc42007c3e0, 0x608900, 0xc42000c140, 0xc420053a60, 0x20, 0x20, 0x5520e0)
        /home/avelino/src/github.com/gin-lang/gin/runtime/runtime.go:140 +0x5ea
    github.com/gin-lang/gin/runtime.(*Context).eval.func1(0xc420053a90, 0xc420053a60, 0xc420053a50, 0xc420053a70, 0xc42007c3e0, 0x608900, 0xc42000c140)
        /home/avelino/src/github.com/gin-lang/gin/runtime/runtime.go:171 +0x7d
    github.com/gin-lang/gin/runtime.(*Context).eval(0xc42007c3e0, 0x608900, 0xc42000c140, 0x0, 0x1, 0xc42000c200, 0x0)
        /home/avelino/src/github.com/gin-lang/gin/runtime/runtime.go:172 +0xeb
    github.com/gin-lang/gin/runtime.(*Context).dispatch(0xc42007c3e0, 0x608900, 0xc42000c1c0, 0xc420053cf0, 0x608940, 0xc42008e3c0, 0x51a480)
        /home/avelino/src/github.com/gin-lang/gin/runtime/runtime.go:125 +0x1c8
    github.com/gin-lang/gin/runtime.(*Context).eval.func1(0xc420053d20, 0xc420053cf0, 0xc420053ce0, 0xc420053d00, 0xc42007c3e0, 0x608900, 0xc42000c1c0)
        /home/avelino/src/github.com/gin-lang/gin/runtime/runtime.go:171 +0x7d
    github.com/gin-lang/gin/runtime.(*Context).eval(0xc42007c3e0, 0x608900, 0xc42000c1c0, 0xc4200806c0, 0x55beb0, 0xc4200a81c0, 0xc4200806d8)
        /home/avelino/src/github.com/gin-lang/gin/runtime/runtime.go:172 +0xeb
    github.com/gin-lang/gin/runtime.(*Context).TryEval(0xc42007c3e0, 0x608900, 0xc42000c1c0, 0x0, 0x0, 0x7fc00c6f2f78, 0x1)
        /home/avelino/src/github.com/gin-lang/gin/runtime/runtime.go:197 +0x3f
    github.com/gin-lang/gin/interative.REPL(0x0, 0x0)
        /home/avelino/src/github.com/gin-lang/gin/interative/interative.go:93 +0x3e5
    main.main()
        /home/avelino/src/github.com/gin-lang/gin/gin.go:25 +0x3c6


>>>
```

**Comment by crgimenes** [comment]
I think this is the correct construction:
```(print (array(1.3)))```
